### ISSUE TITLE
[feat]: custom registry, parallel fetch, and more

### ISSUE THREAD

**Issue by seognil** [T-Specht/ts-typie#5]
Ok, it's back,

---

Thanks for the tool sir~
It looks awesome.

I made some improvements for my own propose
(Almost everything is rewrited now LOL)

- searching package.json up
- remove unused or deprecated types
- add @types/node manually (into fetch list)
- parallel fetching and use custom registry (for speed reason, e.g. I'm in China, so https://registry.npm.taobao.org/ is faster than the original https://registry.npmjs.org/)
- some details like a progress spinner

And for projecting

- add test
- update build system
- update readme

+ update package.json
  - add `files`, only keeps app.js for publish
  - add my self as a contributor
  - update version to 3.x.x

I've already done these with local `npm link`, and using it for my projects
It's covering all my requirements by one command now~ very handy

I can make a PR or we discuss it later if you like~
check my branch https://github.com/seognil-contributor/ts-typie/tree/refactoring

---

It may still remain some bug to fix now

**Comment by T-Specht** [comment]
Could you please elaborate on your ideas and add them to the issue again?

**Comment by seognil** [comment]
I had some implement issues yesterday, so I closed this, sorry >_<

well... I'd reopen it if possible

**Comment by seognil** [comment]
@T-Specht  hi there, any ideas?

**Comment by T-Specht** [comment]
I’ll try to have a more detailed look at it today, thanks 👌🏼

**Comment by seognil** [comment]
@T-Specht Hi there

I refactored that again and made my own version https://github.com/seognil-lab/type-done
(maybe combine with `npm-check` later for better accuracy and performance)

This issue can be closed, Thanks anyway~
